# Generated by Django 5.2.7 on 2025-12-09 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_dietplan_description_dietplan_target_calories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealfooditem',
            unique_together=set(),
        ),
    ]
