# Generated by Django 5.2.7 on 2025-12-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_alter_mealfooditem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='options_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('cheat', 'Cheat meal'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
