# Generated by Django 5.2.7 on 2025-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_program_description_alter_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='max_reps',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum reps for rep ranges', null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='min_reps',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum reps for rep ranges', null=True),
        ),
    ]
