# Generated by Django 5.2.7 on 2025-12-09 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_workoutexercise_max_reps_workoutexercise_min_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='durantion',
            field=models.IntegerField(default=4, help_text='Duration of the program in weeks'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='training.program')),
            ],
        ),
    ]
