# Generated by Django 5.2.7 on 2026-01-08 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_studentevaluation'),
        ('training', '0006_program_durantion_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='program',
        ),
        migrations.AddField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='teachers.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='training.folder'),
        ),
    ]
