# Generated by Django 5.2.7 on 2026-01-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoLesson', '0002_alter_videolesson_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='category',
            field=models.CharField(choices=[('theory', 'Teoria'), ('technique', 'Técnica'), ('practice', 'Prática'), ('nutrition', 'Nutrição'), ('cutting', 'Cutting'), ('bulking', 'Bulking'), ('sports_nutrition', 'Nutrição Esportiva'), ('supplementation', 'Suplementação'), ('muscle_recovery', 'Recuperação Muscular'), ('stretching_mobility', 'Alongamento e Mobilidade')], default='theory', max_length=32),
        ),
    ]
