# Generated by Django 5.2.7 on 2026-01-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_category_exercise_equipment_exercise_force_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
    ]
